const readLine=require('readline-sync')
readLine.question('enter a noun');
readLine.question('enter a verb');
readLine.question('enter a plural noun');
readLine.question('enter a noun');
readLine.question('enter a adjective');
readLine.question('enter a verb');
readLine.question('enter a noun');
readLine.question('enter a adjective');
readLine.question('enter a noun');
readLine.question('enter a verb');
readLine.question('enter a plural noun');
readLine.question('enter a plural noun');
readLine.question('enter a verb');
readLine.question('enter a noun');
readLine.question('enter a adjective');
readLine.question('enter a noun');
readLine.question('enter a verb');
readLine.question('enter a plural noun');
readLine.question('enter a noun');